#!/usr/bin/env bash
#This is a script that configures a new Ubuntu machine nginx
sudo apt-get update

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y
sudo echo "frontend codimentaldev.tech
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 530464-web-01 54.197.128.246:80 check
        server 530464-web-02 54.237.90.186:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
