#!/usr/bin/env bash
# a Bash script that displays:
#+ To infinity and beyond indefinitely
#+ With a sleep 2 in between each iteration
#+  I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"; exit' SIGTERM
word="To infinity and beyond"
while true
do
	echo "$word"
	sleep 2
done
