#!/usr/bin/env bash
# a Bash script that displays Best School 10 times, but for the 9th iteration,
#+ displays Best School and then Hi on a new line.


word="Best School"
counter=0

while [ $counter -lt 10 ]
do
	if [ $counter -eq 8 ]
	then
		echo "$word"
		echo "Hi"
	else
		echo "$word"
	fi
	((counter++))
done
