#!/usr/bin/env bash
# Fixes a container such that the following:
# a.nginx must be running as nginx user
# b. ginx must be listening on all active IPs on port 8080

chown nginx:nginx /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx start
